######################################################################
# Automatically generated by qmake (2.01a) mar. fvr. 9 13:12:19 2010
######################################################################

TEMPLATE = app
TARGET = a2riView
DEPENDPATH += . src include/UI src/UI
INCLUDEPATH += . include/UI
LIBS += -lgsl -lgslcblas -la2ri -lGLEW

QT += opengl

# Input
HEADERS += include/UI/glwidget.hpp include/UI/mainwindow.hpp include/UI/menu.hpp
SOURCES += src/main.cpp \
           src/UI/glwidget.cpp \
           src/UI/mainwindow.cpp \
           src/UI/menu.cpp

target.path    = /usr/local/bin/A2RIVIEW

INSTALLS       = target

